name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose windows-latest if you want to run on Windows

    steps:
      # Check out the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'  # Set to the appropriate .NET version

      # Restore the NuGet packages
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build the project
        run: dotnet build --configuration Release

      # Run tests (optional, but highly recommended for CI)
      - name: Run tests
        run: dotnet test --configuration Release --no-build

      # (Optional) Publish the build artifacts to an output directory (e.g., for deployment)
      - name: Publish output
        run: dotnet publish --configuration Release --output ./publish



